
-- DDL for schema sonyshop
DROP SCHEMA IF EXISTS sonyshop;
CREATE SCHEMA IF NOT EXISTS sonyshop;

-- DDL for Table categories
DROP TABLE IF EXISTS sonyshop.categories;
CREATE TABLE IF NOT EXISTS sonyshop.categories (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(45) NOT NULL,
    TAG VARCHAR(45) NOT NULL,
    IMAGE_NAME VARCHAR(200) NOT NULL,
    RATING INT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_CATEGORY_ID_UNIQUE (ID ASC),
    UNIQUE INDEX IDX_NAME_UNIQUE (NAME ASC),
    UNIQUE INDEX IDX_TAG_UNIQUE (TAG ASC));

-- DDL for Table users
DROP TABLE IF EXISTS sonyshop.users;
CREATE TABLE IF NOT EXISTS sonyshop.users (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(45) NOT NULL,
    SURNAME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH VARCHAR(20) NOT NULL,
    BALANCE INT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_USER_ID_UNIQUE (ID ASC),
    UNIQUE INDEX IDX_EMAIL_UNIQUE (EMAIL ASC));

-- DDL for Table orders
DROP TABLE IF EXISTS sonyshop.orders;
CREATE TABLE IF NOT EXISTS sonyshop.orders (
    ID INT NOT NULL AUTO_INCREMENT,
    PRICE INT NOT NULL,
    DATE VARCHAR(20) NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_ID_UNIQUE (ID ASC),
    CONSTRAINT FK_ORDERS_USER_ID_USERS_ID
        FOREIGN KEY (USER_ID)
        REFERENCES sonyshop.users (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE);

-- DDL for Table products
DROP TABLE IF EXISTS sonyshop.products;
CREATE TABLE IF NOT EXISTS sonyshop.products (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL,
    IMAGE_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(400) NULL,
    PRICE INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_ID_UNIQUE (ID ASC),
    CONSTRAINT FK_PRODUCTS_CATEGORY_ID_CATEGORIES_ID
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES sonyshop.categories (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE);

-- DDL for Table orders_products
DROP TABLE IF EXISTS sonyshop.orders_products;
CREATE TABLE IF NOT EXISTS sonyshop.orders_products (
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT FK_ORDERS_PRODUCTS_ORDER_ID_ORDERS_ID
        FOREIGN KEY (ORDER_ID)
        REFERENCES sonyshop.orders (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
        CONSTRAINT FK_ORDERS_PRODUCTS_PRODUCT_ID_PRODUCTS_ID
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES sonyshop.products (ID));